# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\x12\x03\x61sr\"0\n\nASRRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"!\n\x08\x41SRReply\x12\x15\n\rtranscription\x18\x01 \x01(\t2<\n\nASRService\x12.\n\nTranscribe\x12\x0f.asr.ASRRequest\x1a\r.asr.ASRReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ASRREQUEST']._serialized_start=18
  _globals['_ASRREQUEST']._serialized_end=66
  _globals['_ASRREPLY']._serialized_start=68
  _globals['_ASRREPLY']._serialized_end=101
  _globals['_ASRSERVICE']._serialized_start=103
  _globals['_ASRSERVICE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
