# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import asr_pb2 as protos_dot_asr__pb2


class ASRServiceStub(object):
    """The ASR service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/asr.ASRService/Transcribe',
                request_serializer=protos_dot_asr__pb2.ASRRequest.SerializeToString,
                response_deserializer=protos_dot_asr__pb2.ASRReply.FromString,
                )
        self.ReloadModel = channel.unary_unary(
                '/asr.ASRService/ReloadModel',
                request_serializer=protos_dot_asr__pb2.ReloadModelRequest.SerializeToString,
                response_deserializer=protos_dot_asr__pb2.ReloadModelReply.FromString,
                )


class ASRServiceServicer(object):
    """The ASR service definition.
    """

    def Transcribe(self, request, context):
        """Sends audio data and receives a transcription.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=protos_dot_asr__pb2.ASRRequest.FromString,
                    response_serializer=protos_dot_asr__pb2.ASRReply.SerializeToString,
            ),
            'ReloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadModel,
                    request_deserializer=protos_dot_asr__pb2.ReloadModelRequest.FromString,
                    response_serializer=protos_dot_asr__pb2.ReloadModelReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asr.ASRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ASRService(object):
    """The ASR service definition.
    """

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/asr.ASRService/Transcribe',
            protos_dot_asr__pb2.ASRRequest.SerializeToString,
            protos_dot_asr__pb2.ASRReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/asr.ASRService/ReloadModel',
            protos_dot_asr__pb2.ReloadModelRequest.SerializeToString,
            protos_dot_asr__pb2.ReloadModelReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
