# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/asr.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/asr.proto\x12\x03\x61sr\"[\n\nASRRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x17\n\x0fwith_timestamps\x18\x03 \x01(\x08\x12\x10\n\x08\x64uration\x18\x04 \x01(\x02\"!\n\x08\x41SRReply\x12\x15\n\rtranscription\x18\x01 \x01(\t\"(\n\x12ReloadModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"#\n\x10ReloadModelReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32}\n\nASRService\x12.\n\nTranscribe\x12\x0f.asr.ASRRequest\x1a\r.asr.ASRReply\"\x00\x12?\n\x0bReloadModel\x12\x17.asr.ReloadModelRequest\x1a\x15.asr.ReloadModelReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.asr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ASRREQUEST']._serialized_start=25
  _globals['_ASRREQUEST']._serialized_end=116
  _globals['_ASRREPLY']._serialized_start=118
  _globals['_ASRREPLY']._serialized_end=151
  _globals['_RELOADMODELREQUEST']._serialized_start=153
  _globals['_RELOADMODELREQUEST']._serialized_end=193
  _globals['_RELOADMODELREPLY']._serialized_start=195
  _globals['_RELOADMODELREPLY']._serialized_end=230
  _globals['_ASRSERVICE']._serialized_start=232
  _globals['_ASRSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
